debian: add socat to runtime dependency
QubesOS/qubes-app-linux-split-gpg2 pull request #15
Opened 2024-07-14 04:42 UTC by zpc0

socat is required to run split-gpg2 correctly.
Fixes QubesOS/qubes-issues#9350
Fixes bd82ba1922ab

2024-07-19 21:35 UTC, marmarek commented
Technically, it's needed by the `split-gpg2` package, not `python3-splitgpg2`

2024-07-19 21:35 UTC, marmarek requested changes
Technically, it's needed by the `split-gpg2` package, not `python3-splitgpg2`

2024-07-23 09:44 UTC, zpc0 commented
> Technically, it's needed by the `split-gpg2` package, not `python3-splitgpg2`

Thank you for review! fixed.

2024-08-08 02:01 UTC, marmarek approved these changes

2024-08-08 02:36 UTC, merged