Various improvements
QubesOS/qubes-app-linux-split-gpg2 pull request #8
Opened 2022-09-14 10:05 UTC by DemiMarie

See individual commit messages for details.

2022-09-18 02:18 UTC, marmarek commented
Mypy (I think rightfully) complains.

2022-09-19 22:49 UTC, DemiMarie commented
PipelineRetryFailed

2022-10-24 13:56 UTC, marmarek requested changes

2022-10-24 13:56 UTC, marmarek commented on splitgpg2/__init__.py
> +                primary_key.subkeys.append(subkey)
Aren't you appending it twice now? It's already done above when finishing processing given subkey.

2022-10-24 13:56 UTC, marmarek commented on splitgpg2/test_server.py
> +    raise AssertionError('Assertions disabled while running tests?')
Please don't do that in Python either.

2022-10-24 22:07 UTC, marmarek approved these changes

2022-10-24 22:41 UTC, merged